/********************************************************************************
** Form generated from reading UI file 'esp_mqtt_config_window.ui'
**
** Created by: Qt User Interface Compiler version 5.13.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_ESP_MQTT_CONFIG_WINDOW_H
#define UI_ESP_MQTT_CONFIG_WINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_ESP_MQTT_Config_Window
{
public:
    QWidget *centralwidget;
    QGroupBox *com_port_groupBox;
    QComboBox *port_list_comboBox;
    QComboBox *baudrate_comboBox;
    QLabel *port_label;
    QLabel *baudrate_label;
    QPushButton *connect_pushButton;
    QPushButton *close_pushButton;
    QLabel *connect_state_label;
    QPlainTextEdit *data_from_com_port_plainTextEdit;
    QGroupBox *mqtt_setting_groupBox;
    QTabWidget *setting_tabWidget;
    QWidget *start_up_tab;
    QGroupBox *groupBox_2;
    QLineEdit *broker_port_lineEdit;
    QPushButton *broker_port_pushButton;
    QPushButton *broker_ip_pushButton;
    QLineEdit *broker_ip_lineEdit;
    QLabel *broker_port_label;
    QLabel *broker_ip_label;
    QGroupBox *groupBox_3;
    QLabel *protocol_level_label;
    QCheckBox *will_flag_checkBox;
    QLabel *will_topic_label;
    QPushButton *password_pushButton;
    QLabel *user_name_label;
    QCheckBox *clean_session_checkBox;
    QLabel *will_message_label;
    QLineEdit *user_name_lineEdit;
    QLabel *password_label;
    QCheckBox *password_flag_checkBox;
    QPushButton *connect_flag_pushButton;
    QPushButton *user_name_pushButton;
    QPushButton *protocol_name_pushButton;
    QComboBox *will_qos_comboBox;
    QLineEdit *will_topic_lineEdit;
    QPushButton *protocol_level_pushButton;
    QLineEdit *protocol_name_lineEdit;
    QLineEdit *will_message_lineEdit;
    QLineEdit *protocol_level_lineEdit;
    QCheckBox *user_flag_checkBox;
    QLineEdit *password_lineEdit;
    QLabel *protocol_name_label;
    QLabel *will_qos_label;
    QPushButton *will_message_pushButton;
    QCheckBox *will_retain_checkBox;
    QPushButton *will_topic_pushButton;
    QLabel *keep_alive_label;
    QPushButton *keep_alive_pushButton;
    QLineEdit *keep_alive_lineEdit;
    QLabel *client_identifier_label;
    QLineEdit *client_identifier_lineEdit;
    QPushButton *client_identifier_pushButton;
    QCheckBox *start_up_general_setting_checkBox;
    QGroupBox *groupBox_4;
    QLabel *max_qos_label;
    QPushButton *topic_filter_pushButton;
    QPushButton *max_qos_pushButton;
    QLabel *topic_filter_label;
    QComboBox *max_qos_comboBox;
    QLineEdit *topic_filter_lineEdit;
    QPushButton *broker_info_setting_to_text;
    QPushButton *connect_packet_setting_to_text;
    QPushButton *subscribe_packet_setting_to_text_3;
    QWidget *publish_tab;
    QCheckBox *publish_general_setting_checkBox;
    QGroupBox *groupBox_5;
    QPlainTextEdit *application_message_plainTextEdit;
    QCheckBox *retain_checkBox;
    QLabel *application_message_label;
    QLineEdit *topic_name_lineEdit;
    QPushButton *topic_name_pushButton;
    QPushButton *message_builder_pushButton;
    QLabel *topic_name_label;
    QCheckBox *dup_flag_checkBox;
    QComboBox *qos_level_comboBox;
    QPushButton *publish_flag_pushButton;
    QLabel *qos_level_label;
    QPushButton *application_message_pushButton;
    QGroupBox *groupBox_6;
    QPushButton *uart_trigger_sign_pushButton;
    QLineEdit *continous_interval_lineEdit;
    QPushButton *continous_interval_pushButton;
    QLabel *uart_trigger_sign_label;
    QComboBox *publish_mode_comboBox;
    QComboBox *trigger_type_comboBox;
    QPushButton *trigger_type_pushButton;
    QPushButton *push_mode_pushButton;
    QLabel *trigger_pin_label;
    QLabel *continous_interval_label;
    QLabel *push_mode_label;
    QLineEdit *uart_trigger_sign_lineEdit;
    QLabel *trigger_type_label;
    QPushButton *trigger_pin_pushButton;
    QLineEdit *trigger_pin_lineEdit;
    QPushButton *publish_packet_setting_to_text;
    QPushButton *activity_config_setting_to_text;
    QWidget *hardware_tab;
    QLabel *label;
    QTabWidget *hardware_tabWidget;
    QWidget *tab;
    QComboBox *pin_5_comboBox;
    QPushButton *pin_14_pushButton;
    QPushButton *pin_5_pushButton;
    QLabel *pin_15_label;
    QComboBox *pin_16_comboBox;
    QLabel *pin_2_label;
    QComboBox *pin_13_comboBox;
    QPushButton *pin_2_pushButton;
    QLabel *pin_5_label;
    QPushButton *pin_0_pushButton;
    QPushButton *pin_15_pushButton;
    QPushButton *pin_4_pushButton;
    QComboBox *pin_0_comboBox;
    QPushButton *pin_13_pushButton;
    QLabel *pin_0_label;
    QLabel *pin_14_label;
    QLabel *pin_16_label;
    QComboBox *pin_4_comboBox;
    QComboBox *pin_14_comboBox;
    QLabel *pin_12_label;
    QLabel *pin_4_label;
    QComboBox *pin_12_comboBox;
    QPushButton *pin_12_pushButton;
    QComboBox *pin_2_comboBox;
    QPushButton *pin_16_pushButton;
    QLabel *pin_13_label;
    QComboBox *pin_15_comboBox;
    QWidget *tab_2;
    QWidget *quick_command;
    QTabWidget *quick_command_tabWidget;
    QWidget *tab_10;
    QGroupBox *get_properties_command_groupBox;
    QPushButton *get_publish_properties_pushButton;
    QPushButton *get_connect_properties_pushButton;
    QPushButton *get_activity_properties_pushButton;
    QPushButton *get_broker_properties_pushButton;
    QPushButton *get_subscribe_properties_pushButton;
    QPushButton *get_pin_mode_properties_pushButton;
    QPushButton *get_all_properties_pushButton;
    QWidget *tab_11;
    QGroupBox *mqtt_command_groupBox;
    QPushButton *disconnect_command_pushButton;
    QPushButton *connect_command_pushButton;
    QPushButton *subscribe_command_pushButton;
    QPushButton *unsubscribe_command_pushButton;
    QPushButton *publish_command_pushButton;
    QPushButton *ping_command_pushButton;
    QWidget *on_received_tab;
    QTabWidget *tabWidget_2;
    QWidget *tab_4;
    QLabel *label_21;
    QLineEdit *lineEdit_15;
    QLabel *label_22;
    QComboBox *comboBox_6;
    QLineEdit *lineEdit_16;
    QComboBox *comboBox_7;
    QLabel *label_23;
    QLabel *label_24;
    QLineEdit *lineEdit_17;
    QComboBox *comboBox_8;
    QLabel *label_25;
    QLabel *label_26;
    QTabWidget *tabWidget_3;
    QWidget *tab_7;
    QPlainTextEdit *plainTextEdit_2;
    QPushButton *file_load_pushButton_2;
    QWidget *tab_9;
    QPlainTextEdit *plainTextEdit_3;
    QPushButton *file_load_pushButton_3;
    QWidget *tab_8;
    QPlainTextEdit *plainTextEdit_4;
    QPushButton *file_load_pushButton_4;
    QWidget *tab_5;
    QWidget *tab_6;
    QCheckBox *append_content_checkBox;
    QPushButton *file_save_pushButton;
    QPushButton *text_to_setting;
    QLabel *file_path_lable;
    QPushButton *file_load_pushButton;
    QLineEdit *file_path_lineEdit;
    QPushButton *submit_all_pushButton;
    QPushButton *setting_to_text;
    QPlainTextEdit *configuration_data_plainTextEdit;
    QPushButton *device_reboot_pushButton;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *ESP_MQTT_Config_Window)
    {
        if (ESP_MQTT_Config_Window->objectName().isEmpty())
            ESP_MQTT_Config_Window->setObjectName(QString::fromUtf8("ESP_MQTT_Config_Window"));
        ESP_MQTT_Config_Window->resize(1204, 664);
        centralwidget = new QWidget(ESP_MQTT_Config_Window);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        com_port_groupBox = new QGroupBox(centralwidget);
        com_port_groupBox->setObjectName(QString::fromUtf8("com_port_groupBox"));
        com_port_groupBox->setGeometry(QRect(790, 10, 401, 611));
        port_list_comboBox = new QComboBox(com_port_groupBox);
        port_list_comboBox->setObjectName(QString::fromUtf8("port_list_comboBox"));
        port_list_comboBox->setGeometry(QRect(20, 40, 141, 22));
        baudrate_comboBox = new QComboBox(com_port_groupBox);
        baudrate_comboBox->addItem(QString());
        baudrate_comboBox->addItem(QString());
        baudrate_comboBox->addItem(QString());
        baudrate_comboBox->addItem(QString());
        baudrate_comboBox->addItem(QString());
        baudrate_comboBox->addItem(QString());
        baudrate_comboBox->addItem(QString());
        baudrate_comboBox->addItem(QString());
        baudrate_comboBox->setObjectName(QString::fromUtf8("baudrate_comboBox"));
        baudrate_comboBox->setEnabled(true);
        baudrate_comboBox->setGeometry(QRect(190, 40, 71, 22));
        port_label = new QLabel(com_port_groupBox);
        port_label->setObjectName(QString::fromUtf8("port_label"));
        port_label->setGeometry(QRect(20, 20, 61, 16));
        baudrate_label = new QLabel(com_port_groupBox);
        baudrate_label->setObjectName(QString::fromUtf8("baudrate_label"));
        baudrate_label->setGeometry(QRect(190, 20, 71, 16));
        connect_pushButton = new QPushButton(com_port_groupBox);
        connect_pushButton->setObjectName(QString::fromUtf8("connect_pushButton"));
        connect_pushButton->setGeometry(QRect(280, 40, 51, 23));
        close_pushButton = new QPushButton(com_port_groupBox);
        close_pushButton->setObjectName(QString::fromUtf8("close_pushButton"));
        close_pushButton->setGeometry(QRect(340, 40, 51, 23));
        connect_state_label = new QLabel(com_port_groupBox);
        connect_state_label->setObjectName(QString::fromUtf8("connect_state_label"));
        connect_state_label->setGeometry(QRect(280, 20, 71, 16));
        data_from_com_port_plainTextEdit = new QPlainTextEdit(com_port_groupBox);
        data_from_com_port_plainTextEdit->setObjectName(QString::fromUtf8("data_from_com_port_plainTextEdit"));
        data_from_com_port_plainTextEdit->setGeometry(QRect(20, 80, 371, 521));
        mqtt_setting_groupBox = new QGroupBox(centralwidget);
        mqtt_setting_groupBox->setObjectName(QString::fromUtf8("mqtt_setting_groupBox"));
        mqtt_setting_groupBox->setGeometry(QRect(10, 10, 771, 611));
        setting_tabWidget = new QTabWidget(mqtt_setting_groupBox);
        setting_tabWidget->setObjectName(QString::fromUtf8("setting_tabWidget"));
        setting_tabWidget->setEnabled(true);
        setting_tabWidget->setGeometry(QRect(20, 20, 401, 581));
        setting_tabWidget->setAutoFillBackground(true);
        start_up_tab = new QWidget();
        start_up_tab->setObjectName(QString::fromUtf8("start_up_tab"));
        groupBox_2 = new QGroupBox(start_up_tab);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(10, 10, 321, 81));
        broker_port_lineEdit = new QLineEdit(groupBox_2);
        broker_port_lineEdit->setObjectName(QString::fromUtf8("broker_port_lineEdit"));
        broker_port_lineEdit->setGeometry(QRect(90, 50, 151, 20));
        broker_port_lineEdit->setReadOnly(false);
        broker_port_lineEdit->setClearButtonEnabled(false);
        broker_port_pushButton = new QPushButton(groupBox_2);
        broker_port_pushButton->setObjectName(QString::fromUtf8("broker_port_pushButton"));
        broker_port_pushButton->setGeometry(QRect(260, 50, 51, 23));
        broker_ip_pushButton = new QPushButton(groupBox_2);
        broker_ip_pushButton->setObjectName(QString::fromUtf8("broker_ip_pushButton"));
        broker_ip_pushButton->setGeometry(QRect(260, 20, 51, 23));
        broker_ip_lineEdit = new QLineEdit(groupBox_2);
        broker_ip_lineEdit->setObjectName(QString::fromUtf8("broker_ip_lineEdit"));
        broker_ip_lineEdit->setGeometry(QRect(90, 20, 151, 20));
        broker_port_label = new QLabel(groupBox_2);
        broker_port_label->setObjectName(QString::fromUtf8("broker_port_label"));
        broker_port_label->setGeometry(QRect(10, 50, 61, 16));
        QFont font;
        font.setBold(true);
        font.setWeight(75);
        broker_port_label->setFont(font);
        broker_ip_label = new QLabel(groupBox_2);
        broker_ip_label->setObjectName(QString::fromUtf8("broker_ip_label"));
        broker_ip_label->setGeometry(QRect(10, 20, 61, 16));
        broker_ip_label->setFont(font);
        groupBox_3 = new QGroupBox(start_up_tab);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(10, 100, 321, 361));
        protocol_level_label = new QLabel(groupBox_3);
        protocol_level_label->setObjectName(QString::fromUtf8("protocol_level_label"));
        protocol_level_label->setGeometry(QRect(10, 80, 71, 16));
        will_flag_checkBox = new QCheckBox(groupBox_3);
        will_flag_checkBox->setObjectName(QString::fromUtf8("will_flag_checkBox"));
        will_flag_checkBox->setGeometry(QRect(120, 130, 91, 17));
        will_topic_label = new QLabel(groupBox_3);
        will_topic_label->setObjectName(QString::fromUtf8("will_topic_label"));
        will_topic_label->setGeometry(QRect(10, 240, 61, 16));
        password_pushButton = new QPushButton(groupBox_3);
        password_pushButton->setObjectName(QString::fromUtf8("password_pushButton"));
        password_pushButton->setGeometry(QRect(260, 330, 51, 23));
        user_name_label = new QLabel(groupBox_3);
        user_name_label->setObjectName(QString::fromUtf8("user_name_label"));
        user_name_label->setGeometry(QRect(10, 300, 61, 16));
        user_name_label->setFont(font);
        clean_session_checkBox = new QCheckBox(groupBox_3);
        clean_session_checkBox->setObjectName(QString::fromUtf8("clean_session_checkBox"));
        clean_session_checkBox->setGeometry(QRect(10, 110, 91, 17));
        clean_session_checkBox->setChecked(false);
        will_message_label = new QLabel(groupBox_3);
        will_message_label->setObjectName(QString::fromUtf8("will_message_label"));
        will_message_label->setGeometry(QRect(10, 270, 71, 16));
        user_name_lineEdit = new QLineEdit(groupBox_3);
        user_name_lineEdit->setObjectName(QString::fromUtf8("user_name_lineEdit"));
        user_name_lineEdit->setGeometry(QRect(90, 300, 151, 20));
        password_label = new QLabel(groupBox_3);
        password_label->setObjectName(QString::fromUtf8("password_label"));
        password_label->setGeometry(QRect(10, 330, 61, 16));
        password_label->setFont(font);
        password_flag_checkBox = new QCheckBox(groupBox_3);
        password_flag_checkBox->setObjectName(QString::fromUtf8("password_flag_checkBox"));
        password_flag_checkBox->setGeometry(QRect(10, 150, 91, 17));
        password_flag_checkBox->setChecked(false);
        password_flag_checkBox->setTristate(false);
        connect_flag_pushButton = new QPushButton(groupBox_3);
        connect_flag_pushButton->setObjectName(QString::fromUtf8("connect_flag_pushButton"));
        connect_flag_pushButton->setGeometry(QRect(260, 110, 51, 61));
        user_name_pushButton = new QPushButton(groupBox_3);
        user_name_pushButton->setObjectName(QString::fromUtf8("user_name_pushButton"));
        user_name_pushButton->setGeometry(QRect(260, 300, 51, 23));
        protocol_name_pushButton = new QPushButton(groupBox_3);
        protocol_name_pushButton->setObjectName(QString::fromUtf8("protocol_name_pushButton"));
        protocol_name_pushButton->setGeometry(QRect(260, 50, 51, 23));
        will_qos_comboBox = new QComboBox(groupBox_3);
        will_qos_comboBox->addItem(QString());
        will_qos_comboBox->addItem(QString());
        will_qos_comboBox->addItem(QString());
        will_qos_comboBox->setObjectName(QString::fromUtf8("will_qos_comboBox"));
        will_qos_comboBox->setEnabled(true);
        will_qos_comboBox->setGeometry(QRect(120, 150, 31, 16));
        will_topic_lineEdit = new QLineEdit(groupBox_3);
        will_topic_lineEdit->setObjectName(QString::fromUtf8("will_topic_lineEdit"));
        will_topic_lineEdit->setEnabled(true);
        will_topic_lineEdit->setGeometry(QRect(90, 240, 151, 20));
        protocol_level_pushButton = new QPushButton(groupBox_3);
        protocol_level_pushButton->setObjectName(QString::fromUtf8("protocol_level_pushButton"));
        protocol_level_pushButton->setGeometry(QRect(260, 80, 51, 23));
        protocol_name_lineEdit = new QLineEdit(groupBox_3);
        protocol_name_lineEdit->setObjectName(QString::fromUtf8("protocol_name_lineEdit"));
        protocol_name_lineEdit->setGeometry(QRect(90, 50, 151, 20));
        will_message_lineEdit = new QLineEdit(groupBox_3);
        will_message_lineEdit->setObjectName(QString::fromUtf8("will_message_lineEdit"));
        will_message_lineEdit->setEnabled(true);
        will_message_lineEdit->setGeometry(QRect(90, 270, 151, 20));
        protocol_level_lineEdit = new QLineEdit(groupBox_3);
        protocol_level_lineEdit->setObjectName(QString::fromUtf8("protocol_level_lineEdit"));
        protocol_level_lineEdit->setGeometry(QRect(90, 80, 151, 20));
        user_flag_checkBox = new QCheckBox(groupBox_3);
        user_flag_checkBox->setObjectName(QString::fromUtf8("user_flag_checkBox"));
        user_flag_checkBox->setGeometry(QRect(120, 110, 91, 17));
        user_flag_checkBox->setChecked(false);
        password_lineEdit = new QLineEdit(groupBox_3);
        password_lineEdit->setObjectName(QString::fromUtf8("password_lineEdit"));
        password_lineEdit->setGeometry(QRect(90, 330, 151, 20));
        protocol_name_label = new QLabel(groupBox_3);
        protocol_name_label->setObjectName(QString::fromUtf8("protocol_name_label"));
        protocol_name_label->setGeometry(QRect(10, 50, 71, 16));
        will_qos_label = new QLabel(groupBox_3);
        will_qos_label->setObjectName(QString::fromUtf8("will_qos_label"));
        will_qos_label->setGeometry(QRect(160, 150, 51, 16));
        will_message_pushButton = new QPushButton(groupBox_3);
        will_message_pushButton->setObjectName(QString::fromUtf8("will_message_pushButton"));
        will_message_pushButton->setEnabled(true);
        will_message_pushButton->setGeometry(QRect(260, 270, 51, 23));
        will_retain_checkBox = new QCheckBox(groupBox_3);
        will_retain_checkBox->setObjectName(QString::fromUtf8("will_retain_checkBox"));
        will_retain_checkBox->setGeometry(QRect(10, 130, 91, 17));
        will_topic_pushButton = new QPushButton(groupBox_3);
        will_topic_pushButton->setObjectName(QString::fromUtf8("will_topic_pushButton"));
        will_topic_pushButton->setEnabled(true);
        will_topic_pushButton->setGeometry(QRect(260, 240, 51, 23));
        keep_alive_label = new QLabel(groupBox_3);
        keep_alive_label->setObjectName(QString::fromUtf8("keep_alive_label"));
        keep_alive_label->setGeometry(QRect(10, 180, 71, 16));
        keep_alive_pushButton = new QPushButton(groupBox_3);
        keep_alive_pushButton->setObjectName(QString::fromUtf8("keep_alive_pushButton"));
        keep_alive_pushButton->setGeometry(QRect(260, 180, 51, 23));
        keep_alive_lineEdit = new QLineEdit(groupBox_3);
        keep_alive_lineEdit->setObjectName(QString::fromUtf8("keep_alive_lineEdit"));
        keep_alive_lineEdit->setGeometry(QRect(90, 180, 151, 20));
        client_identifier_label = new QLabel(groupBox_3);
        client_identifier_label->setObjectName(QString::fromUtf8("client_identifier_label"));
        client_identifier_label->setGeometry(QRect(10, 210, 81, 16));
        client_identifier_lineEdit = new QLineEdit(groupBox_3);
        client_identifier_lineEdit->setObjectName(QString::fromUtf8("client_identifier_lineEdit"));
        client_identifier_lineEdit->setGeometry(QRect(90, 210, 151, 20));
        client_identifier_pushButton = new QPushButton(groupBox_3);
        client_identifier_pushButton->setObjectName(QString::fromUtf8("client_identifier_pushButton"));
        client_identifier_pushButton->setGeometry(QRect(260, 210, 51, 23));
        start_up_general_setting_checkBox = new QCheckBox(groupBox_3);
        start_up_general_setting_checkBox->setObjectName(QString::fromUtf8("start_up_general_setting_checkBox"));
        start_up_general_setting_checkBox->setGeometry(QRect(10, 20, 101, 17));
        start_up_general_setting_checkBox->setChecked(false);
        groupBox_4 = new QGroupBox(start_up_tab);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(10, 470, 321, 81));
        max_qos_label = new QLabel(groupBox_4);
        max_qos_label->setObjectName(QString::fromUtf8("max_qos_label"));
        max_qos_label->setGeometry(QRect(10, 50, 61, 16));
        topic_filter_pushButton = new QPushButton(groupBox_4);
        topic_filter_pushButton->setObjectName(QString::fromUtf8("topic_filter_pushButton"));
        topic_filter_pushButton->setGeometry(QRect(260, 20, 51, 23));
        max_qos_pushButton = new QPushButton(groupBox_4);
        max_qos_pushButton->setObjectName(QString::fromUtf8("max_qos_pushButton"));
        max_qos_pushButton->setGeometry(QRect(260, 50, 51, 23));
        topic_filter_label = new QLabel(groupBox_4);
        topic_filter_label->setObjectName(QString::fromUtf8("topic_filter_label"));
        topic_filter_label->setGeometry(QRect(10, 20, 61, 16));
        topic_filter_label->setFont(font);
        max_qos_comboBox = new QComboBox(groupBox_4);
        max_qos_comboBox->addItem(QString());
        max_qos_comboBox->addItem(QString());
        max_qos_comboBox->addItem(QString());
        max_qos_comboBox->setObjectName(QString::fromUtf8("max_qos_comboBox"));
        max_qos_comboBox->setGeometry(QRect(190, 50, 51, 22));
        topic_filter_lineEdit = new QLineEdit(groupBox_4);
        topic_filter_lineEdit->setObjectName(QString::fromUtf8("topic_filter_lineEdit"));
        topic_filter_lineEdit->setGeometry(QRect(90, 20, 151, 20));
        broker_info_setting_to_text = new QPushButton(start_up_tab);
        broker_info_setting_to_text->setObjectName(QString::fromUtf8("broker_info_setting_to_text"));
        broker_info_setting_to_text->setGeometry(QRect(340, 40, 31, 23));
        connect_packet_setting_to_text = new QPushButton(start_up_tab);
        connect_packet_setting_to_text->setObjectName(QString::fromUtf8("connect_packet_setting_to_text"));
        connect_packet_setting_to_text->setGeometry(QRect(340, 260, 31, 23));
        subscribe_packet_setting_to_text_3 = new QPushButton(start_up_tab);
        subscribe_packet_setting_to_text_3->setObjectName(QString::fromUtf8("subscribe_packet_setting_to_text_3"));
        subscribe_packet_setting_to_text_3->setGeometry(QRect(340, 500, 31, 23));
        setting_tabWidget->addTab(start_up_tab, QString());
        groupBox_4->raise();
        groupBox_3->raise();
        groupBox_2->raise();
        broker_info_setting_to_text->raise();
        connect_packet_setting_to_text->raise();
        subscribe_packet_setting_to_text_3->raise();
        publish_tab = new QWidget();
        publish_tab->setObjectName(QString::fromUtf8("publish_tab"));
        publish_general_setting_checkBox = new QCheckBox(publish_tab);
        publish_general_setting_checkBox->setObjectName(QString::fromUtf8("publish_general_setting_checkBox"));
        publish_general_setting_checkBox->setGeometry(QRect(10, 10, 101, 17));
        groupBox_5 = new QGroupBox(publish_tab);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(10, 50, 321, 231));
        application_message_plainTextEdit = new QPlainTextEdit(groupBox_5);
        application_message_plainTextEdit->setObjectName(QString::fromUtf8("application_message_plainTextEdit"));
        application_message_plainTextEdit->setGeometry(QRect(90, 120, 151, 91));
        retain_checkBox = new QCheckBox(groupBox_5);
        retain_checkBox->setObjectName(QString::fromUtf8("retain_checkBox"));
        retain_checkBox->setGeometry(QRect(10, 20, 91, 17));
        application_message_label = new QLabel(groupBox_5);
        application_message_label->setObjectName(QString::fromUtf8("application_message_label"));
        application_message_label->setGeometry(QRect(10, 150, 71, 31));
        topic_name_lineEdit = new QLineEdit(groupBox_5);
        topic_name_lineEdit->setObjectName(QString::fromUtf8("topic_name_lineEdit"));
        topic_name_lineEdit->setGeometry(QRect(90, 90, 151, 20));
        topic_name_pushButton = new QPushButton(groupBox_5);
        topic_name_pushButton->setObjectName(QString::fromUtf8("topic_name_pushButton"));
        topic_name_pushButton->setGeometry(QRect(260, 90, 51, 23));
        message_builder_pushButton = new QPushButton(groupBox_5);
        message_builder_pushButton->setObjectName(QString::fromUtf8("message_builder_pushButton"));
        message_builder_pushButton->setGeometry(QRect(250, 170, 61, 41));
        topic_name_label = new QLabel(groupBox_5);
        topic_name_label->setObjectName(QString::fromUtf8("topic_name_label"));
        topic_name_label->setGeometry(QRect(10, 90, 71, 16));
        topic_name_label->setFont(font);
        dup_flag_checkBox = new QCheckBox(groupBox_5);
        dup_flag_checkBox->setObjectName(QString::fromUtf8("dup_flag_checkBox"));
        dup_flag_checkBox->setGeometry(QRect(10, 40, 70, 17));
        qos_level_comboBox = new QComboBox(groupBox_5);
        qos_level_comboBox->addItem(QString());
        qos_level_comboBox->addItem(QString());
        qos_level_comboBox->addItem(QString());
        qos_level_comboBox->setObjectName(QString::fromUtf8("qos_level_comboBox"));
        qos_level_comboBox->setGeometry(QRect(190, 20, 51, 22));
        publish_flag_pushButton = new QPushButton(groupBox_5);
        publish_flag_pushButton->setObjectName(QString::fromUtf8("publish_flag_pushButton"));
        publish_flag_pushButton->setGeometry(QRect(260, 20, 51, 41));
        qos_level_label = new QLabel(groupBox_5);
        qos_level_label->setObjectName(QString::fromUtf8("qos_level_label"));
        qos_level_label->setGeometry(QRect(130, 20, 51, 16));
        application_message_pushButton = new QPushButton(groupBox_5);
        application_message_pushButton->setObjectName(QString::fromUtf8("application_message_pushButton"));
        application_message_pushButton->setGeometry(QRect(260, 120, 51, 41));
        groupBox_6 = new QGroupBox(publish_tab);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(10, 300, 321, 181));
        uart_trigger_sign_pushButton = new QPushButton(groupBox_6);
        uart_trigger_sign_pushButton->setObjectName(QString::fromUtf8("uart_trigger_sign_pushButton"));
        uart_trigger_sign_pushButton->setGeometry(QRect(260, 140, 51, 23));
        continous_interval_lineEdit = new QLineEdit(groupBox_6);
        continous_interval_lineEdit->setObjectName(QString::fromUtf8("continous_interval_lineEdit"));
        continous_interval_lineEdit->setGeometry(QRect(170, 50, 71, 20));
        continous_interval_pushButton = new QPushButton(groupBox_6);
        continous_interval_pushButton->setObjectName(QString::fromUtf8("continous_interval_pushButton"));
        continous_interval_pushButton->setGeometry(QRect(260, 50, 51, 23));
        uart_trigger_sign_label = new QLabel(groupBox_6);
        uart_trigger_sign_label->setObjectName(QString::fromUtf8("uart_trigger_sign_label"));
        uart_trigger_sign_label->setGeometry(QRect(10, 140, 81, 16));
        publish_mode_comboBox = new QComboBox(groupBox_6);
        publish_mode_comboBox->addItem(QString());
        publish_mode_comboBox->addItem(QString());
        publish_mode_comboBox->setObjectName(QString::fromUtf8("publish_mode_comboBox"));
        publish_mode_comboBox->setGeometry(QRect(170, 20, 71, 22));
        trigger_type_comboBox = new QComboBox(groupBox_6);
        trigger_type_comboBox->addItem(QString());
        trigger_type_comboBox->addItem(QString());
        trigger_type_comboBox->addItem(QString());
        trigger_type_comboBox->setObjectName(QString::fromUtf8("trigger_type_comboBox"));
        trigger_type_comboBox->setGeometry(QRect(130, 80, 111, 22));
        trigger_type_pushButton = new QPushButton(groupBox_6);
        trigger_type_pushButton->setObjectName(QString::fromUtf8("trigger_type_pushButton"));
        trigger_type_pushButton->setGeometry(QRect(260, 80, 51, 23));
        push_mode_pushButton = new QPushButton(groupBox_6);
        push_mode_pushButton->setObjectName(QString::fromUtf8("push_mode_pushButton"));
        push_mode_pushButton->setGeometry(QRect(260, 20, 51, 23));
        trigger_pin_label = new QLabel(groupBox_6);
        trigger_pin_label->setObjectName(QString::fromUtf8("trigger_pin_label"));
        trigger_pin_label->setGeometry(QRect(10, 110, 71, 16));
        continous_interval_label = new QLabel(groupBox_6);
        continous_interval_label->setObjectName(QString::fromUtf8("continous_interval_label"));
        continous_interval_label->setGeometry(QRect(10, 40, 91, 31));
        push_mode_label = new QLabel(groupBox_6);
        push_mode_label->setObjectName(QString::fromUtf8("push_mode_label"));
        push_mode_label->setGeometry(QRect(10, 20, 71, 16));
        uart_trigger_sign_lineEdit = new QLineEdit(groupBox_6);
        uart_trigger_sign_lineEdit->setObjectName(QString::fromUtf8("uart_trigger_sign_lineEdit"));
        uart_trigger_sign_lineEdit->setGeometry(QRect(170, 140, 71, 20));
        trigger_type_label = new QLabel(groupBox_6);
        trigger_type_label->setObjectName(QString::fromUtf8("trigger_type_label"));
        trigger_type_label->setGeometry(QRect(10, 70, 61, 31));
        trigger_pin_pushButton = new QPushButton(groupBox_6);
        trigger_pin_pushButton->setObjectName(QString::fromUtf8("trigger_pin_pushButton"));
        trigger_pin_pushButton->setGeometry(QRect(260, 110, 51, 23));
        trigger_pin_lineEdit = new QLineEdit(groupBox_6);
        trigger_pin_lineEdit->setObjectName(QString::fromUtf8("trigger_pin_lineEdit"));
        trigger_pin_lineEdit->setGeometry(QRect(170, 110, 71, 20));
        publish_packet_setting_to_text = new QPushButton(publish_tab);
        publish_packet_setting_to_text->setObjectName(QString::fromUtf8("publish_packet_setting_to_text"));
        publish_packet_setting_to_text->setGeometry(QRect(350, 160, 31, 23));
        activity_config_setting_to_text = new QPushButton(publish_tab);
        activity_config_setting_to_text->setObjectName(QString::fromUtf8("activity_config_setting_to_text"));
        activity_config_setting_to_text->setGeometry(QRect(350, 370, 31, 23));
        setting_tabWidget->addTab(publish_tab, QString());
        groupBox_5->raise();
        groupBox_6->raise();
        publish_general_setting_checkBox->raise();
        publish_packet_setting_to_text->raise();
        activity_config_setting_to_text->raise();
        hardware_tab = new QWidget();
        hardware_tab->setObjectName(QString::fromUtf8("hardware_tab"));
        label = new QLabel(hardware_tab);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 330, 441, 211));
        label->setPixmap(QPixmap(QString::fromUtf8("NodeMCU_pinout.PNG")));
        label->setScaledContents(true);
        hardware_tabWidget = new QTabWidget(hardware_tab);
        hardware_tabWidget->setObjectName(QString::fromUtf8("hardware_tabWidget"));
        hardware_tabWidget->setGeometry(QRect(10, 10, 431, 311));
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        pin_5_comboBox = new QComboBox(tab);
        pin_5_comboBox->addItem(QString());
        pin_5_comboBox->addItem(QString());
        pin_5_comboBox->addItem(QString());
        pin_5_comboBox->setObjectName(QString::fromUtf8("pin_5_comboBox"));
        pin_5_comboBox->setGeometry(QRect(100, 40, 181, 22));
        pin_14_pushButton = new QPushButton(tab);
        pin_14_pushButton->setObjectName(QString::fromUtf8("pin_14_pushButton"));
        pin_14_pushButton->setGeometry(QRect(300, 160, 51, 23));
        pin_5_pushButton = new QPushButton(tab);
        pin_5_pushButton->setObjectName(QString::fromUtf8("pin_5_pushButton"));
        pin_5_pushButton->setGeometry(QRect(300, 40, 51, 23));
        pin_15_label = new QLabel(tab);
        pin_15_label->setObjectName(QString::fromUtf8("pin_15_label"));
        pin_15_label->setGeometry(QRect(10, 250, 101, 21));
        QFont font1;
        font1.setPointSize(16);
        font1.setBold(false);
        font1.setWeight(50);
        pin_15_label->setFont(font1);
        pin_16_comboBox = new QComboBox(tab);
        pin_16_comboBox->addItem(QString());
        pin_16_comboBox->addItem(QString());
        pin_16_comboBox->addItem(QString());
        pin_16_comboBox->setObjectName(QString::fromUtf8("pin_16_comboBox"));
        pin_16_comboBox->setGeometry(QRect(100, 10, 181, 22));
        pin_2_label = new QLabel(tab);
        pin_2_label->setObjectName(QString::fromUtf8("pin_2_label"));
        pin_2_label->setGeometry(QRect(10, 130, 101, 21));
        pin_2_label->setFont(font1);
        pin_13_comboBox = new QComboBox(tab);
        pin_13_comboBox->addItem(QString());
        pin_13_comboBox->addItem(QString());
        pin_13_comboBox->addItem(QString());
        pin_13_comboBox->setObjectName(QString::fromUtf8("pin_13_comboBox"));
        pin_13_comboBox->setGeometry(QRect(100, 220, 181, 22));
        pin_2_pushButton = new QPushButton(tab);
        pin_2_pushButton->setObjectName(QString::fromUtf8("pin_2_pushButton"));
        pin_2_pushButton->setGeometry(QRect(300, 130, 51, 23));
        pin_5_label = new QLabel(tab);
        pin_5_label->setObjectName(QString::fromUtf8("pin_5_label"));
        pin_5_label->setGeometry(QRect(10, 40, 101, 21));
        pin_5_label->setFont(font1);
        pin_0_pushButton = new QPushButton(tab);
        pin_0_pushButton->setObjectName(QString::fromUtf8("pin_0_pushButton"));
        pin_0_pushButton->setGeometry(QRect(300, 100, 51, 23));
        pin_15_pushButton = new QPushButton(tab);
        pin_15_pushButton->setObjectName(QString::fromUtf8("pin_15_pushButton"));
        pin_15_pushButton->setGeometry(QRect(300, 250, 51, 23));
        pin_4_pushButton = new QPushButton(tab);
        pin_4_pushButton->setObjectName(QString::fromUtf8("pin_4_pushButton"));
        pin_4_pushButton->setGeometry(QRect(300, 70, 51, 23));
        pin_0_comboBox = new QComboBox(tab);
        pin_0_comboBox->addItem(QString());
        pin_0_comboBox->addItem(QString());
        pin_0_comboBox->addItem(QString());
        pin_0_comboBox->setObjectName(QString::fromUtf8("pin_0_comboBox"));
        pin_0_comboBox->setGeometry(QRect(100, 100, 181, 22));
        pin_13_pushButton = new QPushButton(tab);
        pin_13_pushButton->setObjectName(QString::fromUtf8("pin_13_pushButton"));
        pin_13_pushButton->setGeometry(QRect(300, 220, 51, 23));
        pin_0_label = new QLabel(tab);
        pin_0_label->setObjectName(QString::fromUtf8("pin_0_label"));
        pin_0_label->setGeometry(QRect(10, 100, 101, 21));
        pin_0_label->setFont(font1);
        pin_14_label = new QLabel(tab);
        pin_14_label->setObjectName(QString::fromUtf8("pin_14_label"));
        pin_14_label->setGeometry(QRect(10, 160, 101, 21));
        pin_14_label->setFont(font1);
        pin_16_label = new QLabel(tab);
        pin_16_label->setObjectName(QString::fromUtf8("pin_16_label"));
        pin_16_label->setGeometry(QRect(10, 10, 101, 21));
        pin_16_label->setFont(font1);
        pin_4_comboBox = new QComboBox(tab);
        pin_4_comboBox->addItem(QString());
        pin_4_comboBox->addItem(QString());
        pin_4_comboBox->addItem(QString());
        pin_4_comboBox->setObjectName(QString::fromUtf8("pin_4_comboBox"));
        pin_4_comboBox->setGeometry(QRect(100, 70, 181, 22));
        pin_14_comboBox = new QComboBox(tab);
        pin_14_comboBox->addItem(QString());
        pin_14_comboBox->addItem(QString());
        pin_14_comboBox->addItem(QString());
        pin_14_comboBox->setObjectName(QString::fromUtf8("pin_14_comboBox"));
        pin_14_comboBox->setGeometry(QRect(100, 160, 181, 22));
        pin_12_label = new QLabel(tab);
        pin_12_label->setObjectName(QString::fromUtf8("pin_12_label"));
        pin_12_label->setGeometry(QRect(10, 190, 91, 21));
        pin_12_label->setFont(font1);
        pin_4_label = new QLabel(tab);
        pin_4_label->setObjectName(QString::fromUtf8("pin_4_label"));
        pin_4_label->setGeometry(QRect(10, 70, 101, 21));
        pin_4_label->setFont(font1);
        pin_12_comboBox = new QComboBox(tab);
        pin_12_comboBox->addItem(QString());
        pin_12_comboBox->addItem(QString());
        pin_12_comboBox->addItem(QString());
        pin_12_comboBox->setObjectName(QString::fromUtf8("pin_12_comboBox"));
        pin_12_comboBox->setGeometry(QRect(100, 190, 181, 22));
        pin_12_pushButton = new QPushButton(tab);
        pin_12_pushButton->setObjectName(QString::fromUtf8("pin_12_pushButton"));
        pin_12_pushButton->setGeometry(QRect(300, 190, 51, 23));
        pin_2_comboBox = new QComboBox(tab);
        pin_2_comboBox->addItem(QString());
        pin_2_comboBox->addItem(QString());
        pin_2_comboBox->addItem(QString());
        pin_2_comboBox->setObjectName(QString::fromUtf8("pin_2_comboBox"));
        pin_2_comboBox->setGeometry(QRect(100, 130, 181, 22));
        pin_16_pushButton = new QPushButton(tab);
        pin_16_pushButton->setObjectName(QString::fromUtf8("pin_16_pushButton"));
        pin_16_pushButton->setGeometry(QRect(300, 10, 51, 23));
        pin_13_label = new QLabel(tab);
        pin_13_label->setObjectName(QString::fromUtf8("pin_13_label"));
        pin_13_label->setGeometry(QRect(10, 220, 101, 21));
        pin_13_label->setFont(font1);
        pin_15_comboBox = new QComboBox(tab);
        pin_15_comboBox->addItem(QString());
        pin_15_comboBox->addItem(QString());
        pin_15_comboBox->addItem(QString());
        pin_15_comboBox->setObjectName(QString::fromUtf8("pin_15_comboBox"));
        pin_15_comboBox->setGeometry(QRect(100, 250, 181, 22));
        hardware_tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        hardware_tabWidget->addTab(tab_2, QString());
        setting_tabWidget->addTab(hardware_tab, QString());
        quick_command = new QWidget();
        quick_command->setObjectName(QString::fromUtf8("quick_command"));
        quick_command_tabWidget = new QTabWidget(quick_command);
        quick_command_tabWidget->setObjectName(QString::fromUtf8("quick_command_tabWidget"));
        quick_command_tabWidget->setGeometry(QRect(10, 10, 371, 531));
        tab_10 = new QWidget();
        tab_10->setObjectName(QString::fromUtf8("tab_10"));
        get_properties_command_groupBox = new QGroupBox(tab_10);
        get_properties_command_groupBox->setObjectName(QString::fromUtf8("get_properties_command_groupBox"));
        get_properties_command_groupBox->setGeometry(QRect(10, 10, 341, 241));
        get_publish_properties_pushButton = new QPushButton(get_properties_command_groupBox);
        get_publish_properties_pushButton->setObjectName(QString::fromUtf8("get_publish_properties_pushButton"));
        get_publish_properties_pushButton->setGeometry(QRect(190, 130, 131, 31));
        get_connect_properties_pushButton = new QPushButton(get_properties_command_groupBox);
        get_connect_properties_pushButton->setObjectName(QString::fromUtf8("get_connect_properties_pushButton"));
        get_connect_properties_pushButton->setGeometry(QRect(190, 30, 131, 31));
        get_activity_properties_pushButton = new QPushButton(get_properties_command_groupBox);
        get_activity_properties_pushButton->setObjectName(QString::fromUtf8("get_activity_properties_pushButton"));
        get_activity_properties_pushButton->setGeometry(QRect(30, 80, 131, 31));
        get_broker_properties_pushButton = new QPushButton(get_properties_command_groupBox);
        get_broker_properties_pushButton->setObjectName(QString::fromUtf8("get_broker_properties_pushButton"));
        get_broker_properties_pushButton->setGeometry(QRect(30, 30, 131, 31));
        get_subscribe_properties_pushButton = new QPushButton(get_properties_command_groupBox);
        get_subscribe_properties_pushButton->setObjectName(QString::fromUtf8("get_subscribe_properties_pushButton"));
        get_subscribe_properties_pushButton->setGeometry(QRect(190, 80, 131, 31));
        get_pin_mode_properties_pushButton = new QPushButton(get_properties_command_groupBox);
        get_pin_mode_properties_pushButton->setObjectName(QString::fromUtf8("get_pin_mode_properties_pushButton"));
        get_pin_mode_properties_pushButton->setGeometry(QRect(30, 130, 131, 31));
        get_all_properties_pushButton = new QPushButton(get_properties_command_groupBox);
        get_all_properties_pushButton->setObjectName(QString::fromUtf8("get_all_properties_pushButton"));
        get_all_properties_pushButton->setGeometry(QRect(90, 180, 151, 41));
        QFont font2;
        font2.setPointSize(8);
        get_all_properties_pushButton->setFont(font2);
        quick_command_tabWidget->addTab(tab_10, QString());
        tab_11 = new QWidget();
        tab_11->setObjectName(QString::fromUtf8("tab_11"));
        mqtt_command_groupBox = new QGroupBox(tab_11);
        mqtt_command_groupBox->setObjectName(QString::fromUtf8("mqtt_command_groupBox"));
        mqtt_command_groupBox->setGeometry(QRect(10, 20, 341, 181));
        disconnect_command_pushButton = new QPushButton(mqtt_command_groupBox);
        disconnect_command_pushButton->setObjectName(QString::fromUtf8("disconnect_command_pushButton"));
        disconnect_command_pushButton->setGeometry(QRect(180, 30, 131, 31));
        disconnect_command_pushButton->setFont(font2);
        connect_command_pushButton = new QPushButton(mqtt_command_groupBox);
        connect_command_pushButton->setObjectName(QString::fromUtf8("connect_command_pushButton"));
        connect_command_pushButton->setGeometry(QRect(20, 30, 131, 31));
        connect_command_pushButton->setFont(font2);
        subscribe_command_pushButton = new QPushButton(mqtt_command_groupBox);
        subscribe_command_pushButton->setObjectName(QString::fromUtf8("subscribe_command_pushButton"));
        subscribe_command_pushButton->setGeometry(QRect(20, 80, 131, 31));
        subscribe_command_pushButton->setFont(font2);
        unsubscribe_command_pushButton = new QPushButton(mqtt_command_groupBox);
        unsubscribe_command_pushButton->setObjectName(QString::fromUtf8("unsubscribe_command_pushButton"));
        unsubscribe_command_pushButton->setGeometry(QRect(180, 80, 131, 31));
        unsubscribe_command_pushButton->setFont(font2);
        publish_command_pushButton = new QPushButton(mqtt_command_groupBox);
        publish_command_pushButton->setObjectName(QString::fromUtf8("publish_command_pushButton"));
        publish_command_pushButton->setGeometry(QRect(20, 130, 131, 31));
        publish_command_pushButton->setFont(font2);
        ping_command_pushButton = new QPushButton(mqtt_command_groupBox);
        ping_command_pushButton->setObjectName(QString::fromUtf8("ping_command_pushButton"));
        ping_command_pushButton->setGeometry(QRect(180, 130, 131, 31));
        ping_command_pushButton->setFont(font2);
        connect_command_pushButton->raise();
        subscribe_command_pushButton->raise();
        unsubscribe_command_pushButton->raise();
        publish_command_pushButton->raise();
        ping_command_pushButton->raise();
        disconnect_command_pushButton->raise();
        quick_command_tabWidget->addTab(tab_11, QString());
        setting_tabWidget->addTab(quick_command, QString());
        on_received_tab = new QWidget();
        on_received_tab->setObjectName(QString::fromUtf8("on_received_tab"));
        tabWidget_2 = new QTabWidget(on_received_tab);
        tabWidget_2->setObjectName(QString::fromUtf8("tabWidget_2"));
        tabWidget_2->setGeometry(QRect(0, 10, 431, 431));
        tab_4 = new QWidget();
        tab_4->setObjectName(QString::fromUtf8("tab_4"));
        label_21 = new QLabel(tab_4);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(20, 20, 81, 16));
        lineEdit_15 = new QLineEdit(tab_4);
        lineEdit_15->setObjectName(QString::fromUtf8("lineEdit_15"));
        lineEdit_15->setGeometry(QRect(100, 20, 113, 20));
        label_22 = new QLabel(tab_4);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(230, 20, 41, 16));
        comboBox_6 = new QComboBox(tab_4);
        comboBox_6->addItem(QString());
        comboBox_6->addItem(QString());
        comboBox_6->addItem(QString());
        comboBox_6->setObjectName(QString::fromUtf8("comboBox_6"));
        comboBox_6->setGeometry(QRect(280, 20, 69, 22));
        lineEdit_16 = new QLineEdit(tab_4);
        lineEdit_16->setObjectName(QString::fromUtf8("lineEdit_16"));
        lineEdit_16->setGeometry(QRect(100, 60, 113, 20));
        comboBox_7 = new QComboBox(tab_4);
        comboBox_7->addItem(QString());
        comboBox_7->addItem(QString());
        comboBox_7->addItem(QString());
        comboBox_7->setObjectName(QString::fromUtf8("comboBox_7"));
        comboBox_7->setGeometry(QRect(280, 60, 69, 22));
        label_23 = new QLabel(tab_4);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(230, 60, 41, 16));
        label_24 = new QLabel(tab_4);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(20, 60, 81, 16));
        lineEdit_17 = new QLineEdit(tab_4);
        lineEdit_17->setObjectName(QString::fromUtf8("lineEdit_17"));
        lineEdit_17->setGeometry(QRect(100, 100, 113, 20));
        comboBox_8 = new QComboBox(tab_4);
        comboBox_8->addItem(QString());
        comboBox_8->addItem(QString());
        comboBox_8->addItem(QString());
        comboBox_8->setObjectName(QString::fromUtf8("comboBox_8"));
        comboBox_8->setGeometry(QRect(280, 100, 69, 22));
        label_25 = new QLabel(tab_4);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(230, 100, 41, 16));
        label_26 = new QLabel(tab_4);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(20, 100, 81, 16));
        tabWidget_3 = new QTabWidget(tab_4);
        tabWidget_3->setObjectName(QString::fromUtf8("tabWidget_3"));
        tabWidget_3->setGeometry(QRect(20, 160, 381, 211));
        tab_7 = new QWidget();
        tab_7->setObjectName(QString::fromUtf8("tab_7"));
        plainTextEdit_2 = new QPlainTextEdit(tab_7);
        plainTextEdit_2->setObjectName(QString::fromUtf8("plainTextEdit_2"));
        plainTextEdit_2->setGeometry(QRect(10, 40, 351, 131));
        file_load_pushButton_2 = new QPushButton(tab_7);
        file_load_pushButton_2->setObjectName(QString::fromUtf8("file_load_pushButton_2"));
        file_load_pushButton_2->setGeometry(QRect(10, 10, 71, 23));
        tabWidget_3->addTab(tab_7, QString());
        tab_9 = new QWidget();
        tab_9->setObjectName(QString::fromUtf8("tab_9"));
        plainTextEdit_3 = new QPlainTextEdit(tab_9);
        plainTextEdit_3->setObjectName(QString::fromUtf8("plainTextEdit_3"));
        plainTextEdit_3->setGeometry(QRect(10, 40, 351, 131));
        file_load_pushButton_3 = new QPushButton(tab_9);
        file_load_pushButton_3->setObjectName(QString::fromUtf8("file_load_pushButton_3"));
        file_load_pushButton_3->setGeometry(QRect(10, 10, 71, 23));
        tabWidget_3->addTab(tab_9, QString());
        tab_8 = new QWidget();
        tab_8->setObjectName(QString::fromUtf8("tab_8"));
        plainTextEdit_4 = new QPlainTextEdit(tab_8);
        plainTextEdit_4->setObjectName(QString::fromUtf8("plainTextEdit_4"));
        plainTextEdit_4->setGeometry(QRect(10, 40, 351, 131));
        file_load_pushButton_4 = new QPushButton(tab_8);
        file_load_pushButton_4->setObjectName(QString::fromUtf8("file_load_pushButton_4"));
        file_load_pushButton_4->setGeometry(QRect(10, 10, 71, 23));
        tabWidget_3->addTab(tab_8, QString());
        tabWidget_2->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QString::fromUtf8("tab_5"));
        tabWidget_2->addTab(tab_5, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QString::fromUtf8("tab_6"));
        tabWidget_2->addTab(tab_6, QString());
        setting_tabWidget->addTab(on_received_tab, QString());
        append_content_checkBox = new QCheckBox(mqtt_setting_groupBox);
        append_content_checkBox->setObjectName(QString::fromUtf8("append_content_checkBox"));
        append_content_checkBox->setGeometry(QRect(470, 100, 101, 17));
        file_save_pushButton = new QPushButton(mqtt_setting_groupBox);
        file_save_pushButton->setObjectName(QString::fromUtf8("file_save_pushButton"));
        file_save_pushButton->setGeometry(QRect(690, 70, 71, 23));
        text_to_setting = new QPushButton(mqtt_setting_groupBox);
        text_to_setting->setObjectName(QString::fromUtf8("text_to_setting"));
        text_to_setting->setGeometry(QRect(430, 340, 31, 23));
        file_path_lable = new QLabel(mqtt_setting_groupBox);
        file_path_lable->setObjectName(QString::fromUtf8("file_path_lable"));
        file_path_lable->setGeometry(QRect(470, 40, 47, 13));
        file_load_pushButton = new QPushButton(mqtt_setting_groupBox);
        file_load_pushButton->setObjectName(QString::fromUtf8("file_load_pushButton"));
        file_load_pushButton->setGeometry(QRect(520, 70, 71, 23));
        file_path_lineEdit = new QLineEdit(mqtt_setting_groupBox);
        file_path_lineEdit->setObjectName(QString::fromUtf8("file_path_lineEdit"));
        file_path_lineEdit->setGeometry(QRect(520, 40, 241, 20));
        submit_all_pushButton = new QPushButton(mqtt_setting_groupBox);
        submit_all_pushButton->setObjectName(QString::fromUtf8("submit_all_pushButton"));
        submit_all_pushButton->setGeometry(QRect(470, 570, 191, 31));
        submit_all_pushButton->setFont(font2);
        setting_to_text = new QPushButton(mqtt_setting_groupBox);
        setting_to_text->setObjectName(QString::fromUtf8("setting_to_text"));
        setting_to_text->setGeometry(QRect(430, 310, 31, 23));
        configuration_data_plainTextEdit = new QPlainTextEdit(mqtt_setting_groupBox);
        configuration_data_plainTextEdit->setObjectName(QString::fromUtf8("configuration_data_plainTextEdit"));
        configuration_data_plainTextEdit->setGeometry(QRect(470, 120, 291, 441));
        device_reboot_pushButton = new QPushButton(mqtt_setting_groupBox);
        device_reboot_pushButton->setObjectName(QString::fromUtf8("device_reboot_pushButton"));
        device_reboot_pushButton->setGeometry(QRect(680, 570, 81, 31));
        device_reboot_pushButton->setFont(font2);
        ESP_MQTT_Config_Window->setCentralWidget(centralwidget);
        mqtt_setting_groupBox->raise();
        com_port_groupBox->raise();
        menubar = new QMenuBar(ESP_MQTT_Config_Window);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1204, 21));
        ESP_MQTT_Config_Window->setMenuBar(menubar);
        statusbar = new QStatusBar(ESP_MQTT_Config_Window);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        ESP_MQTT_Config_Window->setStatusBar(statusbar);

        retranslateUi(ESP_MQTT_Config_Window);

        setting_tabWidget->setCurrentIndex(1);
        hardware_tabWidget->setCurrentIndex(0);
        quick_command_tabWidget->setCurrentIndex(1);
        tabWidget_2->setCurrentIndex(0);
        tabWidget_3->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(ESP_MQTT_Config_Window);
    } // setupUi

    void retranslateUi(QMainWindow *ESP_MQTT_Config_Window)
    {
        ESP_MQTT_Config_Window->setWindowTitle(QCoreApplication::translate("ESP_MQTT_Config_Window", "MainWindow", nullptr));
        com_port_groupBox->setTitle(QCoreApplication::translate("ESP_MQTT_Config_Window", "COM Port", nullptr));
        baudrate_comboBox->setItemText(0, QCoreApplication::translate("ESP_MQTT_Config_Window", "115200", nullptr));
        baudrate_comboBox->setItemText(1, QCoreApplication::translate("ESP_MQTT_Config_Window", "9600", nullptr));
        baudrate_comboBox->setItemText(2, QCoreApplication::translate("ESP_MQTT_Config_Window", "38400", nullptr));
        baudrate_comboBox->setItemText(3, QCoreApplication::translate("ESP_MQTT_Config_Window", "57600", nullptr));
        baudrate_comboBox->setItemText(4, QCoreApplication::translate("ESP_MQTT_Config_Window", "1200", nullptr));
        baudrate_comboBox->setItemText(5, QCoreApplication::translate("ESP_MQTT_Config_Window", "2400", nullptr));
        baudrate_comboBox->setItemText(6, QCoreApplication::translate("ESP_MQTT_Config_Window", "4800", nullptr));
        baudrate_comboBox->setItemText(7, QCoreApplication::translate("ESP_MQTT_Config_Window", "19200", nullptr));

        port_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Port", nullptr));
        baudrate_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "BaudRate", nullptr));
        connect_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Connect", nullptr));
        close_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Close", nullptr));
        connect_state_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Disconnected", nullptr));
        mqtt_setting_groupBox->setTitle(QCoreApplication::translate("ESP_MQTT_Config_Window", "MQTT Setting", nullptr));
        groupBox_2->setTitle(QCoreApplication::translate("ESP_MQTT_Config_Window", "Broker Infomation", nullptr));
        broker_port_lineEdit->setText(QString());
        broker_port_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        broker_ip_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        broker_ip_lineEdit->setPlaceholderText(QString());
        broker_port_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Broker Port", nullptr));
        broker_ip_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Broker IP", nullptr));
        groupBox_3->setTitle(QCoreApplication::translate("ESP_MQTT_Config_Window", "Connect Packet", nullptr));
        protocol_level_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Protocol Level", nullptr));
        will_flag_checkBox->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "       Will Flag", nullptr));
        will_topic_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Will Topic", nullptr));
        password_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        user_name_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "User Name", nullptr));
        clean_session_checkBox->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Clean Session", nullptr));
        will_message_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Will Message", nullptr));
        user_name_lineEdit->setText(QString());
        password_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Password", nullptr));
        password_flag_checkBox->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Password Flag", nullptr));
        connect_flag_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        user_name_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        protocol_name_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        will_qos_comboBox->setItemText(0, QCoreApplication::translate("ESP_MQTT_Config_Window", "0", nullptr));
        will_qos_comboBox->setItemText(1, QCoreApplication::translate("ESP_MQTT_Config_Window", "1", nullptr));
        will_qos_comboBox->setItemText(2, QCoreApplication::translate("ESP_MQTT_Config_Window", "2", nullptr));

        will_topic_lineEdit->setText(QString());
        protocol_level_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        protocol_name_lineEdit->setText(QString());
        will_message_lineEdit->setText(QString());
        protocol_level_lineEdit->setText(QString());
        user_flag_checkBox->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "        User Flag", nullptr));
        password_lineEdit->setText(QString());
        protocol_name_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Protocol Name", nullptr));
        will_qos_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Will QoS", nullptr));
        will_message_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        will_retain_checkBox->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Will Retain", nullptr));
        will_topic_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        keep_alive_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Keep Alive (s)", nullptr));
        keep_alive_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        keep_alive_lineEdit->setText(QString());
        client_identifier_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Client Identifier", nullptr));
        client_identifier_lineEdit->setText(QString());
        client_identifier_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        start_up_general_setting_checkBox->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "General Setting", nullptr));
        groupBox_4->setTitle(QCoreApplication::translate("ESP_MQTT_Config_Window", "Subscribe Packet", nullptr));
        max_qos_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Max QoS", nullptr));
        topic_filter_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        max_qos_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        topic_filter_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Topic filter", nullptr));
        max_qos_comboBox->setItemText(0, QCoreApplication::translate("ESP_MQTT_Config_Window", "0", nullptr));
        max_qos_comboBox->setItemText(1, QCoreApplication::translate("ESP_MQTT_Config_Window", "1", nullptr));
        max_qos_comboBox->setItemText(2, QCoreApplication::translate("ESP_MQTT_Config_Window", "2", nullptr));

        broker_info_setting_to_text->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "->", nullptr));
        connect_packet_setting_to_text->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "->", nullptr));
        subscribe_packet_setting_to_text_3->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "->", nullptr));
        setting_tabWidget->setTabText(setting_tabWidget->indexOf(start_up_tab), QCoreApplication::translate("ESP_MQTT_Config_Window", "Start up", nullptr));
        publish_general_setting_checkBox->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "General Setting", nullptr));
        groupBox_5->setTitle(QCoreApplication::translate("ESP_MQTT_Config_Window", "Publish Packet", nullptr));
        retain_checkBox->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "RETAIN", nullptr));
        application_message_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Application\n"
"Message", nullptr));
        topic_name_lineEdit->setText(QString());
        topic_name_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        message_builder_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Message\n"
"Builder", nullptr));
        topic_name_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Topic Name", nullptr));
        dup_flag_checkBox->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "DUP Flag", nullptr));
        qos_level_comboBox->setItemText(0, QCoreApplication::translate("ESP_MQTT_Config_Window", "0", nullptr));
        qos_level_comboBox->setItemText(1, QCoreApplication::translate("ESP_MQTT_Config_Window", "1", nullptr));
        qos_level_comboBox->setItemText(2, QCoreApplication::translate("ESP_MQTT_Config_Window", "2", nullptr));

        publish_flag_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        qos_level_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "QoS Level", nullptr));
        application_message_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        groupBox_6->setTitle(QCoreApplication::translate("ESP_MQTT_Config_Window", "Activity", nullptr));
        uart_trigger_sign_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        continous_interval_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        uart_trigger_sign_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Uart Trigge Sign", nullptr));
        publish_mode_comboBox->setItemText(0, QCoreApplication::translate("ESP_MQTT_Config_Window", "Continous", nullptr));
        publish_mode_comboBox->setItemText(1, QCoreApplication::translate("ESP_MQTT_Config_Window", "Trigger", nullptr));

        trigger_type_comboBox->setItemText(0, QCoreApplication::translate("ESP_MQTT_Config_Window", "Rising and Falling", nullptr));
        trigger_type_comboBox->setItemText(1, QCoreApplication::translate("ESP_MQTT_Config_Window", "Rising", nullptr));
        trigger_type_comboBox->setItemText(2, QCoreApplication::translate("ESP_MQTT_Config_Window", "Falling", nullptr));

        trigger_type_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        push_mode_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        trigger_pin_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Trigger Pin", nullptr));
        continous_interval_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Continous Interval\n"
"(ms) (300ms min)", nullptr));
        push_mode_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Publish Mode", nullptr));
        uart_trigger_sign_lineEdit->setText(QString());
        trigger_type_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Trigger Type", nullptr));
        trigger_pin_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        trigger_pin_lineEdit->setText(QString());
        publish_packet_setting_to_text->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "->", nullptr));
        activity_config_setting_to_text->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "->", nullptr));
        setting_tabWidget->setTabText(setting_tabWidget->indexOf(publish_tab), QCoreApplication::translate("ESP_MQTT_Config_Window", "Publish", nullptr));
        label->setText(QString());
        pin_5_comboBox->setItemText(0, QCoreApplication::translate("ESP_MQTT_Config_Window", "INPUT_MODE", nullptr));
        pin_5_comboBox->setItemText(1, QCoreApplication::translate("ESP_MQTT_Config_Window", "OUTPUT_MODE", nullptr));
        pin_5_comboBox->setItemText(2, QCoreApplication::translate("ESP_MQTT_Config_Window", "INPUT_PULLUP_MODE", nullptr));

        pin_14_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        pin_5_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        pin_15_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "GPIO15", nullptr));
        pin_16_comboBox->setItemText(0, QCoreApplication::translate("ESP_MQTT_Config_Window", "INPUT_MODE", nullptr));
        pin_16_comboBox->setItemText(1, QCoreApplication::translate("ESP_MQTT_Config_Window", "OUTPUT_MODE", nullptr));
        pin_16_comboBox->setItemText(2, QCoreApplication::translate("ESP_MQTT_Config_Window", "INPUT_PULLUP_MODE", nullptr));

        pin_2_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "GPIO2", nullptr));
        pin_13_comboBox->setItemText(0, QCoreApplication::translate("ESP_MQTT_Config_Window", "INPUT_MODE", nullptr));
        pin_13_comboBox->setItemText(1, QCoreApplication::translate("ESP_MQTT_Config_Window", "OUTPUT_MODE", nullptr));
        pin_13_comboBox->setItemText(2, QCoreApplication::translate("ESP_MQTT_Config_Window", "INPUT_PULLUP_MODE", nullptr));

        pin_2_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        pin_5_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "GPIO5", nullptr));
        pin_0_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        pin_15_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        pin_4_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        pin_0_comboBox->setItemText(0, QCoreApplication::translate("ESP_MQTT_Config_Window", "INPUT_MODE", nullptr));
        pin_0_comboBox->setItemText(1, QCoreApplication::translate("ESP_MQTT_Config_Window", "OUTPUT_MODE", nullptr));
        pin_0_comboBox->setItemText(2, QCoreApplication::translate("ESP_MQTT_Config_Window", "INPUT_PULLUP_MODE", nullptr));

        pin_13_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        pin_0_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "GPIO0", nullptr));
        pin_14_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "GPIO14", nullptr));
        pin_16_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "GPIO16", nullptr));
        pin_4_comboBox->setItemText(0, QCoreApplication::translate("ESP_MQTT_Config_Window", "INPUT_MODE", nullptr));
        pin_4_comboBox->setItemText(1, QCoreApplication::translate("ESP_MQTT_Config_Window", "OUTPUT_MODE", nullptr));
        pin_4_comboBox->setItemText(2, QCoreApplication::translate("ESP_MQTT_Config_Window", "INPUT_PULLUP_MODE", nullptr));

        pin_14_comboBox->setItemText(0, QCoreApplication::translate("ESP_MQTT_Config_Window", "INPUT_MODE", nullptr));
        pin_14_comboBox->setItemText(1, QCoreApplication::translate("ESP_MQTT_Config_Window", "OUTPUT_MODE", nullptr));
        pin_14_comboBox->setItemText(2, QCoreApplication::translate("ESP_MQTT_Config_Window", "INPUT_PULLUP_MODE", nullptr));

        pin_12_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "GPIO12", nullptr));
        pin_4_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "GPIO4", nullptr));
        pin_12_comboBox->setItemText(0, QCoreApplication::translate("ESP_MQTT_Config_Window", "INPUT_MODE", nullptr));
        pin_12_comboBox->setItemText(1, QCoreApplication::translate("ESP_MQTT_Config_Window", "OUTPUT_MODE", nullptr));
        pin_12_comboBox->setItemText(2, QCoreApplication::translate("ESP_MQTT_Config_Window", "INPUT_PULLUP_MODE", nullptr));

        pin_12_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        pin_2_comboBox->setItemText(0, QCoreApplication::translate("ESP_MQTT_Config_Window", "INPUT_MODE", nullptr));
        pin_2_comboBox->setItemText(1, QCoreApplication::translate("ESP_MQTT_Config_Window", "OUTPUT_MODE", nullptr));
        pin_2_comboBox->setItemText(2, QCoreApplication::translate("ESP_MQTT_Config_Window", "INPUT_PULLUP_MODE", nullptr));

        pin_16_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit", nullptr));
        pin_13_label->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "GPIO13", nullptr));
        pin_15_comboBox->setItemText(0, QCoreApplication::translate("ESP_MQTT_Config_Window", "INPUT_MODE", nullptr));
        pin_15_comboBox->setItemText(1, QCoreApplication::translate("ESP_MQTT_Config_Window", "OUTPUT_MODE", nullptr));
        pin_15_comboBox->setItemText(2, QCoreApplication::translate("ESP_MQTT_Config_Window", "INPUT_PULLUP_MODE", nullptr));

        hardware_tabWidget->setTabText(hardware_tabWidget->indexOf(tab), QCoreApplication::translate("ESP_MQTT_Config_Window", "GPIO", nullptr));
        hardware_tabWidget->setTabText(hardware_tabWidget->indexOf(tab_2), QCoreApplication::translate("ESP_MQTT_Config_Window", "...", nullptr));
        setting_tabWidget->setTabText(setting_tabWidget->indexOf(hardware_tab), QCoreApplication::translate("ESP_MQTT_Config_Window", "Hardware", nullptr));
        get_properties_command_groupBox->setTitle(QCoreApplication::translate("ESP_MQTT_Config_Window", "Get Properties Command", nullptr));
        get_publish_properties_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Get Publish Properties", nullptr));
        get_connect_properties_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Get Connect Properties", nullptr));
        get_activity_properties_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Get Avtivity  Properties", nullptr));
        get_broker_properties_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Get Broker Properties", nullptr));
        get_subscribe_properties_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Get Subscribe Properties", nullptr));
        get_pin_mode_properties_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Get Pin Mode Properties", nullptr));
        get_all_properties_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Get All Properties", nullptr));
        quick_command_tabWidget->setTabText(quick_command_tabWidget->indexOf(tab_10), QCoreApplication::translate("ESP_MQTT_Config_Window", "General Command", nullptr));
        mqtt_command_groupBox->setTitle(QCoreApplication::translate("ESP_MQTT_Config_Window", "MQTT Command", nullptr));
        disconnect_command_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Disconnect", nullptr));
        connect_command_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Connect", nullptr));
        subscribe_command_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Subscribe", nullptr));
        unsubscribe_command_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Unsubscribe", nullptr));
        publish_command_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Publish", nullptr));
        ping_command_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Ping", nullptr));
        quick_command_tabWidget->setTabText(quick_command_tabWidget->indexOf(tab_11), QCoreApplication::translate("ESP_MQTT_Config_Window", "MQTT Command", nullptr));
        setting_tabWidget->setTabText(setting_tabWidget->indexOf(quick_command), QCoreApplication::translate("ESP_MQTT_Config_Window", "Quick Command", nullptr));
        label_21->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "If Command =", nullptr));
        label_22->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Do task", nullptr));
        comboBox_6->setItemText(0, QCoreApplication::translate("ESP_MQTT_Config_Window", "1", nullptr));
        comboBox_6->setItemText(1, QCoreApplication::translate("ESP_MQTT_Config_Window", "2", nullptr));
        comboBox_6->setItemText(2, QCoreApplication::translate("ESP_MQTT_Config_Window", "3", nullptr));

        comboBox_7->setItemText(0, QCoreApplication::translate("ESP_MQTT_Config_Window", "1", nullptr));
        comboBox_7->setItemText(1, QCoreApplication::translate("ESP_MQTT_Config_Window", "2", nullptr));
        comboBox_7->setItemText(2, QCoreApplication::translate("ESP_MQTT_Config_Window", "3", nullptr));

        label_23->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Do task", nullptr));
        label_24->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "If Command =", nullptr));
        comboBox_8->setItemText(0, QCoreApplication::translate("ESP_MQTT_Config_Window", "1", nullptr));
        comboBox_8->setItemText(1, QCoreApplication::translate("ESP_MQTT_Config_Window", "2", nullptr));
        comboBox_8->setItemText(2, QCoreApplication::translate("ESP_MQTT_Config_Window", "3", nullptr));

        label_25->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Do task", nullptr));
        label_26->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "If Command =", nullptr));
        file_load_pushButton_2->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Define Task", nullptr));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_7), QCoreApplication::translate("ESP_MQTT_Config_Window", "Task 1", nullptr));
        file_load_pushButton_3->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Define Task", nullptr));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_9), QCoreApplication::translate("ESP_MQTT_Config_Window", "Task 2", nullptr));
        file_load_pushButton_4->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Define Task", nullptr));
        tabWidget_3->setTabText(tabWidget_3->indexOf(tab_8), QCoreApplication::translate("ESP_MQTT_Config_Window", "Task 3", nullptr));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_4), QCoreApplication::translate("ESP_MQTT_Config_Window", "Model A", nullptr));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_5), QCoreApplication::translate("ESP_MQTT_Config_Window", "Model B", nullptr));
        tabWidget_2->setTabText(tabWidget_2->indexOf(tab_6), QCoreApplication::translate("ESP_MQTT_Config_Window", "Model C", nullptr));
        setting_tabWidget->setTabText(setting_tabWidget->indexOf(on_received_tab), QCoreApplication::translate("ESP_MQTT_Config_Window", "On Received", nullptr));
        append_content_checkBox->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Append Content", nullptr));
        file_save_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Save", nullptr));
        text_to_setting->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "<-", nullptr));
        file_path_lable->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "File Path", nullptr));
        file_load_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Load", nullptr));
        submit_all_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Submit All", nullptr));
        setting_to_text->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "->", nullptr));
        device_reboot_pushButton->setText(QCoreApplication::translate("ESP_MQTT_Config_Window", "Device Reboot", nullptr));
    } // retranslateUi

};

namespace Ui {
    class ESP_MQTT_Config_Window: public Ui_ESP_MQTT_Config_Window {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_ESP_MQTT_CONFIG_WINDOW_H
